### PR TITLE
[My first PR check the diffs of course] Added tips

### PR DESCRIPTION
**Pull request by TheEt1234**
No comment

### CODE REVIEW

**Comment by blaumeise20** [comment]
This looks very cool! There is one thing that isn't perfect: the font. Please update the font style to match the rest of the app!

**Comment by TheEt1234** [comment]
Sorry i didn't notice

**Comment by TheEt1234** [comment]
I changed the font, is it good now?

**Comment by blaumeise20** [comment]
Very cool! Thanks!

**Pull request merged**
