### PR TITLE
Add "Controls" In README.md

### PR DESCRIPTION
**Pull request by MeBadDev**
I think it is pretty important

### CODE REVIEW

**Comment by MeBadDev** [comment]
Yay this is my first pr

**Comment by blaumeise20** [comment]
Wow thanks! One thing I would like to change: could you use a list instead of multiple paragraphs and make the "key" bold?

**Comment by MeBadDev** [comment]
> Wow thanks! One thing I would like to change: could you use a list instead of multiple paragraphs and make the "key" bold?

Done!

**Comment by blaumeise20** [comment]
Cool, just remove the newlines in between please!

**Review by blaumeise20 — APPROVED** [review]
Great, thanks!

**Pull request merged**
